// // import OnBoardingScreen from "pages/SubPage/OnBoardingPage/OnBoardingScreen" 
// import LoginScreen from "pages/SubPage/AuthenticatePage/LoginScreen" 
// import RegisterScreen from "pages/SubPage/AuthenticatePage/RegisterScreen" 
// import ForgetPasswordScreen from "pages/SubPage/AuthenticatePage/ForgetPasswordScreen" 
// import WelcomeScreen from "pages/SubPage/PersonalizationPage/WelcomeScreen" 
// import PersonalizationScreen from "pages/SubPage/PersonalizationPage/PersonalizationScreen" 
// import ConfirmOTPScreen from "pages/SubPage/AuthenticatePage/ConfirmOTPScreen"
// import FinishPersonalizationScreen from "pages/SubPage/PersonalizationPage/FinishPersonalizationScreen"
// import EmailSentScreen from "pages/SubPage/AuthenticatePage/EmailSentScreen"
// export {FinishPersonalizationScreen, EmailSentScreen,ConfirmOTPScreen,LoginScreen,RegisterScreen,ForgetPasswordScreen,WelcomeScreen,PersonalizationScreen}